### PR TITLE
Add openMind

### PR DESCRIPTION
**Pull request by silenteyesoncode**
## Changes Made:

- Added my project to the "Apps built with React Native" section of the README.md file.
- Included a brief description of my project.
- Added a link to my project's GitHub repository.
- Included a screenshot of my app.

I believe my project would be a great addition to the list of apps built with React Native. It showcases the power and versatility of the framework and could serve as an inspiration for other developers. I have followed the guidelines provided in the repo's CONTRIBUTING.md file and believe that my project meets the criteria for inclusion.

Thank you for considering my contribution!

### CODE REVIEW

**Comment by GantMan** [comment]
Your link is to convene.  Looks like a copy and paste where you forgot to update.

**Comment by GantMan** [comment]
can you add a 1 paragraph description to the top of the readme for people to know what the app does?  A little more specifics.

I know you have a video, but I would like a bit of text, as well.

**Comment by silenteyesoncode** [comment]
Updated the Readme 
please have a look

https://github.com/The-Unleashed-Club/openMind

**Comment by GantMan** [comment]
Excellent - will merge.  Don't forget to set up your social card for the repo so when people share the link it will unfurl an image.

**Pull request merged**
