### PR TITLE
Add Brolly - Personal insurance manager

### PR DESCRIPTION
**Pull request by lpetkovic**

### CODE REVIEW

**Comment by lanapetkovic** [comment]
Hi, this is not an open source project, therefore, no github link was provided.

**Comment by lucasbento** [comment]
@lanapetkovic: the `README.md` clearly states that this is a list for **only open source React Native apps**.

**Comment by GantMan** [comment]
Hi @lpetkovic - If we could have made it clearer that this is for open source, please let me know.  The goal is community source code from released apps.

**Comment by lpetkovic** [comment]
Hi, my mistake, for overseeing that the list contains only open source apps. I'm sorry.

**Pull request closed without merging**
