### PR TITLE
Add shields.io badge to show last commit, github star count & React Native version

### PR DESCRIPTION
**Pull request by alexakasanjeev**
Hi @GantMan 

[shields.io](https://shields.io/category/activity) provides badges which can be used to show data about the repository like github stars, last commit date, a dependency version, and they will be auto update every time the repo is changed. This will help keep the list always show most up to date data which can help user to decide which project they want to look on.

**For example**
Last commit on this repo Last commit
Github stars on this repo Github Star
React Native version on [MageCart](https://github.com/alexakasanjeev/magento_react_native) repo React Native version

We can update similarly for all the projects mentioned in the list

**TODO**
1. Add Shield badge to show React Native version 
2. Add Shield badge to last commit date
3. Add Shield badge to show star count on github repo

You can see in this branch, I have updated for first 10 list item, if you think it is right, I can continue updating the list bit by bit, and once finally done we can merge this pull request. What do you think?

>  Don't merge right now, work isn't complete

### CODE REVIEW

**Comment by GantMan** [comment]
Very cool!

**Comment by alexakasanjeev** [comment]
Hi @GantMan I haven't completed this, I just implemented in first 10 list item, I wanted your approval, I will update same for the rest of the list

**Comment by GantMan** [comment]
I saw there were only 10 done.   I figured you got busy and would come back and do them over time.    It felt fine that only the top few were done, and it sets the standard if anyone sends a PR in the meantime :)

Sorry to early merge on ya, but I figured it's ok if it updates in parts.

**Comment by alexakasanjeev** [comment]
No problem, I would prefer to do slow update because there is lot of copy & paste involved, and its very easy to add some error. But I would try to complete this list as soon as possible :)

Thanks

**Comment by GantMan** [comment]
how's this going?

**Comment by alexakasanjeev** [comment]
Sorry I forgot, will get back soon, I was binge watching boruto, my bad 😅

**Pull request merged**
