### PR TITLE
add covidinfo and tictactoe apps

### PR DESCRIPTION
**Pull request by siddsarkar**

### CODE REVIEW

**Comment by alexakasanjeev** [comment]
Hi @siddsarkar Thank you so much for your contribution, 

Can you please add your two items after the repo **Covid19**, instead at the top.

**Comment by siddsarkar** [comment]
Done ! @alexakasanjeev  thanks for your response!

**Comment by GantMan** [comment]
This looks good to me.   @alexakasanjeev - what do you think?

**Comment by GantMan** [comment]
@siddsarkar - please fix the conflicts and I'll merge.

**Comment by siddsarkar** [comment]
I already fixed as suggested by @alexakasanjeev please verify @GantMan

**Comment by GantMan** [comment]
yup, your changes were good, but there's a new standing merge conflict.  If you can fix that, I'll hit merge.

**Pull request closed without merging**
