### PR TITLE
Add COVID Alert app

### PR DESCRIPTION
**Pull request by a7medev**
The COVID Alert app is a great example of making a React Native app accessible and it has been used by Shopify in [this workshop](https://www.youtube.com/watch?v=fI6rtLpJcAY) to showcase accessibility in React Native.

### CODE REVIEW

**Comment by GantMan** [comment]
The app seems to be retired, though.  I'm not sure if it fits.  People can't experience it without a lot of process.

**Comment by a7medev** [comment]
@GantMan Yes but I think the source code is already in a pretty good state. What do you think?

**Comment by GantMan** [comment]
Do you have access to the readme doc that this links to?  Could you add that video up top so people could see the app?

If then, I'd def add.

**Comment by a7medev** [comment]
@GantMan Unfortunately I don't have access to this repository, I opened this PR because I think it can actually be helpful for people learning about accessibility.
We can add the video link in the description of the app if you want.

**Comment by GantMan** [comment]
Good points, added!

**Pull request merged**
