### PR TITLE
Adding files to new_branch

### PR DESCRIPTION
**Pull request by nishant-666**

### CODE REVIEW

**Comment by GantMan** [comment]
Oh hai!  What's this?

**Comment by nishant-666** [comment]
I wanted to add my project to React Native Projects Repo. I submitted a
pull request as instructed on the page.

**Comment by GantMan** [comment]
I appreciate that @nishant-666 

Generally, all projects are kept in their home locations, and a PR to the README.md links to your repo.   We don't generally house the code here.   That way you can update your project as needed.

**Comment by nishant-666** [comment]
Okay!

**Pull request closed without merging**
